### ISSUE TITLE
notificationUrl/Instant Payment Notification

### ISSUE THREAD

**Issue by bevdam** [PayUMEA/payu-mea-code-examples-rpp-php#1]
Hi 

I would like to know what format the IPN data is return in ,is it a GET or a POST .In fact how can do tests to see if my system is working correctly with IPN. How can i trigger the test server ,Staging 3 to send me an IPN .

Thanks

**Comment by RamizMohamed** [comment]
Hi

Please refer to our knowledge base articles at http://help.payu.co.za/display/developers/Instant+Payment+Notification, in this regard.

The Staging Integration Store 3 test store sends IPN's by default and the credentials can be located at http://help.payu.co.za/display/developers/Test+Credentials.

Regards
